### PR TITLE
V0.1.1

### PR DESCRIPTION
**Pull request by PedroFerreiradaCosta**
Fixes

 * Remove Apple DS_store files
 * Set threshold_alpha to 1e9, similar to Tipping's code.

### CODE REVIEW

**Comment by Warvito** [comment]
Hi @PedroFerreiradaCosta 
Why did you closed this branch?

**Review by Warvito — APPROVED** [review]
Looks great!

**Comment by Warvito** [comment]
Could you please deploy it to pipy?

**Comment by PedroFerreiradaCosta** [comment]
Done!

**Pull request merged**
